name: rsa_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  encrypt: ^5.0.1
  pointycastle: ^3.7.2
  shared_preferences: ^2.0.20
  basic_utils: ^5.5.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
